program: train.py
name: hyperparam_search
method: bayes
metric:
  goal: minimize
  name: val_error
parameters:
  lr_pi:
    min: 0.0001
    max: 0.01
  lr_ip: 
    min: 0.0001
    max: 0.01
  n_samples:
    min: 1000
    max: 10000
  actfunc:
    values: ['sigm', 'hardsigm', 'tanh', 'logexp', 'softrelu']
  noise: 
    min: 0.1
    max: 0.3
  tau_weights:
    min: 1
    max: 30
  tau_neu:
    min: 1
    max: 5
  hidden_size:
    values: [20, 30, 50] 
  
