wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0006817904562713748
lr_pi:
  value: 0.0023527279320156385
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 1
