_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": linux-x86_64
actfunc:
    value: softrelu
lr_ip:
    value: 0.002961142716718452
lr_pi:
    value: 0.0035319369729655734
tau_neu:
    value: 1
tau_weights:
    value: 7
