wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.00047496410023382897
lr_pi:
  value: 0.007639559628353386
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 27
