wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0003249399237481605
lr_pi:
  value: 0.005101455608422034
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 1
