wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.00012809725517592532
lr_pi:
  value: 0.008544704180428343
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 6
