wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.00018826324451100385
lr_pi:
  value: 0.0028521471849376045
n_samples:
  value: 10000
noise:
  value: 0.3
tau_weights:
  value: 29
