wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0002483059913650438
lr_pi:
  value: 0.0014968326549659305
n_samples:
  value: 10000
noise:
  value: 0.3
tau_weights:
  value: 30
