wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0001030033256638233
lr_pi:
  value: 0.008061989521619437
n_samples:
  value: 10000
noise:
  value: 0.3
tau_weights:
  value: 29
