wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.000980043151082981
lr_pi:
  value: 0.004400490342428543
n_samples:
  value: 10000
noise:
  value: 0.3
tau_weights:
  value: 30
