_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": linux-x86_64
actfunc:
    value: hardsigm
hidden_size:
    value: 30
lr_ip:
    value: 0.0016713381348923292
lr_pi:
    value: 0.006588636468160773
n_samples:
    value: 670
noise:
    value: 0.19899895360798908
tau_neu:
    value: 3
tau_weights:
    value: 14
