wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0005466105884613354
lr_pi:
  value: 0.009830079143285816
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 4
