wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.000291667428104037
lr_pi:
  value: 0.006379045146550869
n_samples:
  value: 1000
noise:
  value: 0.3
tau_weights:
  value: 3
