wandb_version: 1

actfunc:
  value: softrelu
hidden_size:
  value: 20
lr_ip:
  value: 0.0004764518753504281
lr_pi:
  value: 0.007293090241707066
n_samples:
  value: 10000
noise:
  value: 0.3
tau_weights:
  value: 18
